### ISSUE TITLE
`bootstrap.jar` : Scala signature package has wrong version, expected: `5.0`, found: `5.2` in `package.class`

### ISSUE THREAD

**Issue by pawelprazak** [VirtusLab/besom#244]
```
    I1016 11:34:29.360219   90932 log.go:81] [error] error while loading package, class file '/var/folders/nr/rqhf2hvn3wn8q_mjysz2gq6m0000gn/T/9121815977791727713/plugins/language-scala-v0.1.1-SNAPSHOT/bootstrap.jar(scala/collection/immutable/package.class)' is broken
    [error] (class java.lang.RuntimeException/error reading Scala signature of package.class: Scala signature package has wrong version
    [error]  expected: 5.0
    [error]  found: 5.2 in package.class)
    [error] /Users/pprazak/repos/besom/integration-tests/resources/executors/scala-cli/Main.scala:6:39: object resourceplugin is not a member of package besom.languageplugin.test
    [error]     val x = besom.languageplugin.test.resourceplugin.standard.customVal
    [error]                                       ^
    [error] /Users/pprazak/repos/besom/integration-tests/resources/executors/scala-cli/Main.scala:7:39: object resourceplugin is not a member of package besom.languageplugin.test
    [error]     val y = besom.languageplugin.test.resourceplugin.external.customVal
    [error]                                       ^
    [error] three errors found
    [error] (Compile / compileIncremental) Compilation failed
    I1016 11:34:29.360235   90932 log.go:81] java.io.IOException: Scala signature package has wrong version
     expected: 5.0
     found: 5.2 in package.class
    	at scala.reflect.internal.pickling.UnPickler$Scan.checkVersion(UnPickler.scala:122)
    	at scala.reflect.internal.pickling.UnPickler$Scan.<init>(UnPickler.scala:64)
    	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:47)
    	at scala.tools.nsc.symtab.classfile.ClassfileParser.unpickleOrParseInnerClasses(ClassfileParser.scala:1176)
    	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:467)
    	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$2(ClassfileParser.scala:160)
    	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:146)
    	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:129)
    	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:343)
    	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:250)
    	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1542)
    	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
    	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:356)
    	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:411)
    	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:313)
    	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:250)
    	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1542)
    	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
    	at scala.reflect.internal.Types$TypeRef.baseClasses(Types.scala:2280)
    	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.init(FindMembers.scala:36)
    	at scala.reflect.internal.tpe.FindMembers$FindMember.init(FindMembers.scala:257)
    	at scala.reflect.internal.Types$Type.$anonfun$findMember$1(Types.scala:1042)
    	at scala.reflect.internal.Types$Type.findMemberInternal$1(Types.scala:1041)
    	at scala.reflect.internal.Types$Type.findMember(Types.scala:1046)
    	at scala.reflect.internal.Types$Type.memberBasedOnName(Types.scala:672)
    	at scala.reflect.internal.Types$Type.member(Types.scala:636)
    	at scala.reflect.internal.Mirrors$RootsBase.getModuleByName(Mirrors.scala:55)
    	at scala.reflect.internal.Mirrors$RootsBase.getRequiredModule(Mirrors.scala:159)
    	at scala.reflect.internal.Mirrors$RootsBase.requiredModule(Mirrors.scala:169)
    	at scala.reflect.internal.Definitions$DefinitionsClass.ListModule$lzycompute(Definitions.scala:483)
    	at scala.reflect.internal.Definitions$DefinitionsClass.ListModule(Definitions.scala:483)
    	at scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3736)
    	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3749)
    	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4939)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4950)
    	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5767)
    	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5812)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5876)
    	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3356)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3356)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2516)
    	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$105(Typers.scala:5742)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:500)
    	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5777)
    	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5812)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:5874)
    	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5732)
    	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5812)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5876)
    	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3356)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3356)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2038)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1904)
    	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5734)
    	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5812)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5876)
    	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3356)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3356)
    	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5444)
    	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5736)
    	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5812)
    	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:114)
    	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:453)
    	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:102)
    	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1509)
    	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1493)
    	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1486)
    	at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1597)
    	at xsbt.CachedCompiler0.run(CompilerBridge.scala:165)
    	at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
    	at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
    	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
    	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
    	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
    	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
    	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
    	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
    	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
    	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
    	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
    	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
    	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:180)
    	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:178)
    	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:464)
    	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
    	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
    	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
    	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
    	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:419)
    	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
    	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:406)
    	at sbt.internal.inc.Incremental$.apply(Incremental.scala:172)
    	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
    	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
    	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
    	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
    	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
    	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2371)
    	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2321)
    	at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:31)
    	at sbt.internal.io.Retry$.apply(Retry.scala:47)
    	at sbt.internal.io.Retry$.apply(Retry.scala:29)
    	at sbt.internal.io.Retry$.apply(Retry.scala:24)
    	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
    	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2319)
    	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
    	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
    	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
    	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
    	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
    	at sbt.Execute.work(Execute.scala:292)
    	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
    	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
    	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    	at java.base/java.lang.Thread.run(Thread.java:1583)
    I1016 11:34:29.360249   90932 log.go:81] GetRequiredPlugins: plugins=[]
    I1016 11:34:29.400663   90932 log.go:81] Run: program=.
    I1016 11:34:29.400681   90932 log.go:73] Language host launching process: /usr/local/bin/sbt-batch run
```

**Comment by pawelprazak** [comment]
OK, the cause was `project/build.properties` in the `scala-cli` executor test causing the executor selector to prefer sbt
