### ISSUE TITLE
Decoding failure on azure-native:logic:listWorkflowTriggerCallbackUrl

### ISSUE THREAD

**Issue by polkx** [VirtusLab/besom#521]
When I try to get value from method `azurenative.logic.listWorkflowTriggerCallbackUrl` the Error shows up about deserializing.

Example in draft request: https://github.com/VirtusLab/besom/pull/520

I think it is related to https://github.com/VirtusLab/besom/issues/432

Stack trace:

```
Diagnostics:
  pulumi:pulumi:Stack (azure-cosmosdb-logicapp-dev):
    Downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala3-library_3/
    Downloaded https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala3-library_3/
    Compiling project (Scala 3.3.1, JVM (11))
    Compiled project (Scala 3.3.1, JVM (11))
    Exception in thread "main" besom.internal.AggregatedDecodingError: azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath: Encountered an error - possible secret - Known(Set(),false,Some(Value(NullValue(NULL_VALUE),UnknownFieldSet(Map()))))
        at besom.internal.AggregatedDecodingError$.apply(codecs.scala:99)
        at besom.internal.ResourceOps.decodeResponse$1$$anonfun$1(ResourceOps.scala:91)
        at besom.internal.Result.flatMap$$anonfun$1(Result.scala:166)
        at besom.internal.Result.runM$$anonfun$7(Result.scala:273)
        at besom.internal.Runtime.flatMapBothM$$anonfun$1$$anonfun$1(Result.scala:118)
        at besom.internal.FutureRuntime.flatMapBoth$$anonfun$1(Result.scala:404)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:477)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
    Caused by: besom.internal.DecodingError: [azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath] azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath: Encountered an error - possible secret - Known(Set(),false,Some(Value(NullValue(NULL_VALUE),UnknownFieldSet(Map()))))
        at besom.internal.DecodingError$.apply(codecs.scala:80)
        at besom.internal.Decoder.decode$$anonfun$1$$anonfun$2(codecs.scala:132)
        at besom.util.NonEmptyVector.map(Validated.scala:167)
        at besom.util.Validated.lmap(Validated.scala:47)
        at besom.internal.Decoder.decode$$anonfun$1(codecs.scala:134)
        at besom.util.Validated$.flatMap$$anonfun$1(Validated.scala:112)
        ... 11 more
    Caused by: besom.internal.DecodingError: [azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath] azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath: Expected a string, got: 'NullValue(NULL_VALUE)'
        at besom.internal.DecodingError$.apply(codecs.scala:80)
        at besom.internal.Decoder$stringDecoder$.mapping(codecs.scala:217)
        at besom.internal.Decoder.decode$$anonfun$1$$anonfun$1(codecs.scala:128)
        at besom.internal.OutputData.traverseValidated(OutputData.scala:93)
        at besom.internal.Decoder.decode$$anonfun$1(codecs.scala:128)
        ... 12 more

    error: an unhandled error occurred: '/opt/homebrew/bin/scala-cli /opt/homebrew/bin/scala-cli run . ' exited with non-zero exit code: 1

    2024.06.18 14:00:36:485 main  ERROR besom.internal.BesomModule.run:70
        besom.internal.AggregatedDecodingError: azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath: Encountered an error - possible secret - Known(Set(),false,Some(Value(NullValue(NULL_VALUE),UnknownFieldSet(Map()))))
                at besom.internal.AggregatedDecodingError$.apply(codecs.scala:99)
                at besom.internal.ResourceOps.decodeResponse$1$$anonfun$1(ResourceOps.scala:91)
                at besom.internal.Result.flatMap$$anonfun$1(Result.scala:166)
                at besom.internal.Result.runM$$anonfun$7(Result.scala:273)
                at besom.internal.Runtime.flatMapBothM$$anonfun$1$$anonfun$1(Result.scala:118)
                at besom.internal.FutureRuntime.flatMapBoth$$anonfun$1(Result.scala:404)
                at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:477)
                at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
        Caused by: besom.internal.DecodingError: [azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath] azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath: Encountered an error - possible secret - Known(Set(),false,Some(Value(NullValue(NULL_VALUE),UnknownFieldSet(Map()))))
                at besom.internal.DecodingError$.apply(codecs.scala:80)
                at besom.internal.Decoder.decode$$anonfun$1$$anonfun$2(codecs.scala:132)
                at besom.util.NonEmptyVector.map(Validated.scala:167)
                at besom.util.Validated.lmap(Validated.scala:47)
                at besom.internal.Decoder.decode$$anonfun$1(codecs.scala:134)
                at besom.util.Validated$.flatMap$$anonfun$1(Validated.scala:112)
                at besom.internal.Result.flatMap$$anonfun$1(Result.scala:166)
                at besom.internal.Result.runM$$anonfun$7(Result.scala:273)
                at besom.internal.Runtime.flatMapBothM$$anonfun$1$$anonfun$1(Result.scala:118)
                at besom.internal.FutureRuntime.flatMapBoth$$anonfun$1(Result.scala:404)
                at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:477)
                at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
        Caused by: besom.internal.DecodingError: [azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath] azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath: Expected a string, got: 'NullValue(NULL_VALUE)'
                at besom.internal.DecodingError$.apply(codecs.scala:80)
                at besom.internal.Decoder$stringDecoder$.mapping(codecs.scala:217)
                at besom.internal.Decoder.decode$$anonfun$1$$anonfun$1(codecs.scala:128)
                at besom.internal.OutputData.traverseValidated(OutputData.scala:93)
                at besom.internal.Decoder.decode$$anonfun$1(codecs.scala:128)
                at besom.util.Validated$.flatMap$$anonfun$1(Validated.scala:112)
                at besom.internal.Result.flatMap$$anonfun$1(Result.scala:166)
                at besom.internal.Result.runM$$anonfun$7(Result.scala:273)
                at besom.internal.Runtime.flatMapBothM$$anonfun$1$$anonfun$1(Result.scala:118)
                at besom.internal.FutureRuntime.flatMapBoth$$anonfun$1(Result.scala:404)
                at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:477)
                at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Comment by lbialy** [comment]
solved partially by #524 - there's still a problem with nullable field:
`besom.internal.DecodingError: [azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath] azure-native:logic:listWorkflowTriggerCallbackUrl().relativePath: Expected a string, got: 'NullValue(NULL_VALUE)'`
