### ISSUE TITLE
Decoding error for `aws.route53.getZone`

### ISSUE THREAD

**Issue by grzegorz-bielski** [VirtusLab/besom#535]
When using:
```scala
//> using scala "3.4.2"
//> using options -Wunused:all -Wvalue-discard -Wnonunit-statement
//> using dep "org.virtuslab::besom-core:0.3.2"
//> using dep org.virtuslab::besom-aws:6.39.0-core.0.3

@main def main = Pulumi.run:
   Stack(
       aws.route53
          .getZone(aws.route53.GetZoneArgs(name = "example.com."))
          .map(_.zoneId)
   )
```
I'm getting following error.
```
Exception in thread "main" besom.internal.AggregatedDecodingError: Decoding Errors [3]:
      aws:route53/getZone:getZone().linkedServiceDescription: Encountered an error - possible secret - Known(Set(),false,Some(Value(NullValue(NULL_VALUE),UnknownFieldSet(Map()))))
      aws:route53/getZone:getZone().linkedServicePrincipal: Encountered an error - possible secret - Known(Set(),false,Some(Value(NullValue(NULL_VALUE),UnknownFieldSet(Map()))))
      aws:route53/getZone:getZone().vpcId: Encountered an error - possible secret - Known(Set(),false,Some(Value(NullValue(NULL_VALUE),UnknownFieldSet(Map()))))
    (with aggregate stack trace)
        at besom.internal.AggregatedDecodingError$.apply(codecs.scala:99)
        at besom.internal.ResourceOps.decodeResponse$1$$anonfun$1(ResourceOps.scala:91)
        at besom.internal.Result.flatMap$$anonfun$1(Result.scala:166)
        at besom.internal.Result.runM$$anonfun$7(Result.scala:273)
        at besom.internal.Runtime.flatMapBothM$$anonfun$1$$anonfun$1(Result.scala:118)
        at besom.internal.FutureRuntime.flatMapBoth$$anonfun$1(Result.scala:404)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:477)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
    Caused by: besom.internal.DecodingError: [aws:route53/getZone:getZone().linkedServiceDescription] aws:route53/getZone:getZone().linkedServiceDescription: Encountered an error - possible secret - Known(Set(),false,Some(Value(NullValue(NULL_VALUE),UnknownFieldSet(Map()))))
        at besom.internal.DecodingError$.apply(codecs.scala:80)
        at besom.internal.Decoder.decode$$anonfun$1$$anonfun$2(codecs.scala:132)
        at besom.util.NonEmptyVector.map(Validated.scala:167)
        at besom.util.Validated.lmap(Validated.scala:47)
        at besom.internal.Decoder.decode$$anonfun$1(codecs.scala:134)
        at besom.util.Validated$.flatMap$$anonfun$1(Validated.scala:112)
        ... 11 more
        Suppressed: besom.internal.DecodingError: [aws:route53/getZone:getZone().linkedServicePrincipal] aws:route53/getZone:getZone().linkedServicePrincipal: Encountered an error - possible secret - Known(Set(),false,Some(Value(NullValue(NULL_VALUE),UnknownFieldSet(Map()))))
                ... 17 more
        Caused by: besom.internal.DecodingError: [aws:route53/getZone:getZone().linkedServicePrincipal] aws:route53/getZone:getZone().linkedServicePrincipal: Expected a string, got: 'NullValue(NULL_VALUE)'
                at besom.internal.DecodingError$.apply(codecs.scala:80)
                at besom.internal.Decoder$stringDecoder$.mapping(codecs.scala:217)
                at besom.internal.Decoder.decode$$anonfun$1$$anonfun$1(codecs.scala:128)
                at besom.internal.OutputData.traverseValidated(OutputData.scala:93)
                at besom.internal.Decoder.decode$$anonfun$1(codecs.scala:128)
                ... 12 more
        Suppressed: besom.internal.DecodingError: [aws:route53/getZone:getZone().vpcId] aws:route53/getZone:getZone().vpcId: Encountered an error - possible secret - Known(Set(),false,Some(Value(NullValue(NULL_VALUE),UnknownFieldSet(Map()))))
                ... 17 more
        Caused by: besom.internal.DecodingError: [aws:route53/getZone:getZone().vpcId] aws:route53/getZone:getZone().vpcId: Expected a string, got: 'NullValue(NULL_VALUE)'
                at besom.internal.DecodingError$.apply(codecs.scala:80)
                at besom.internal.Decoder$stringDecoder$.mapping(codecs.scala:217)
                at besom.internal.Decoder.decode$$anonfun$1$$anonfun$1(codecs.scala:128)
                at besom.internal.OutputData.traverseValidated(OutputData.scala:93)
                at besom.internal.Decoder.decode$$anonfun$1(codecs.scala:128)
                ... 12 more
    Caused by: besom.internal.DecodingError: [aws:route53/getZone:getZone().linkedServiceDescription] aws:route53/getZone:getZone().linkedServiceDescription: Expected a string, got: 'NullValue(NULL_VALUE)'
        at besom.internal.DecodingError$.apply(codecs.scala:80)
        at besom.internal.Decoder$stringDecoder$.mapping(codecs.scala:217)
        at besom.internal.Decoder.decode$$anonfun$1$$anonfun$1(codecs.scala:128)
        at besom.internal.OutputData.traverseValidated(OutputData.scala:93)
        at besom.internal.Decoder.decode$$anonfun$1(codecs.scala:128)
        ... 12 more
```
Possibly the same thing as in: https://github.com/VirtusLab/besom/issues/432

Is there any known workaround?

**Comment by lbialy** [comment]
If you don't plan to use any of the following fields:

```
linkedServiceDescription
linkedServicePrincipal
vpcId
```

then the answer is yes as the workaround in form of more granular, field level decoding is already in main branch awaiting 0.4.0 release. Actual fix for this problem would be either to:
a) get Pulumi to fix the schema to mark these fields as optional if they are mistakenly marked as non-optional or
b) if they are indeed non-optional but terraform provider is buggy, to get AWS to fix the provider ooooor
c) for us to maintain per-package registry of field optionality overrides in our codegen that would be consulted during package generation to apply type adjustments for fields that do indeed show up as nulls in runtime and crash user apps. I am strongly biased towards c) currently even though my co-maintainers voiced vocal opposition to this as it's basically a hack that requires maintenance effort on our side. I think we *should* do special case handling for unexpected nullable fields as they are so common (thanks to null-unsafe langs being used in the whole infra stack beneath us) and not do any special handling for actual type errors, ie we expect a Double but there's a String in data - these things have to be raised as issues upstream. For nullable fields I think we should just implement the overrides and post issues to Pulumi / TF concurrently, this should solve the problem on our side quickly and once the upstream fixes things on their side we can just drop the override. I'll make an issue and see if we can fit it for 0.4 release.

**Comment by grzegorz-bielski** [comment]
Thanks for the quick and detailed response!

I'm won't be using these fields, so I'll just wait for `0.4.0`.
In the meantime I'll settle for hardcoding / using aws sdk to get that zone id.

I have no opinion on internals of Besom, but looking at issues I can see that such situations are not that rare and some form of documented escape hatch would be useful.

**Comment by lbialy** [comment]
Yes, granular decoding alleviates the problem to "if you don't need that field, it won't block you" level but I think we should improve the error messages so that they are more actionable (I think it also was partially implemented already, error messages will contain a clickable link to open an issue on gh that is already filled with relevant context from the error).

**Comment by jchapuis** [comment]
Just a heads up that I have run into the same issue, looking forward for the next release then!

**Comment by lbialy** [comment]
I owe all of you a sitrep. 

0.4.0 has already happened in late March. 

Unfortunately it shipped with a rather nasty bugs in both schema resolution in publishing scripts and in component parenting rules. First one caused a situation where partial schemas were used to build provider packages (because Pulumi tooling uses slightly different schemas for provider wire protocol than the ones that are stored in respective github repos of providers) and thanks to that some aliased resources might be missing in the published packages. Second one is more severe and more insidious - we dropped the implicit context in most APIs and rewritten the internals of Output to work as a reader monad that propagates Context on its own. This however introduced a semantic change that affects all component resources defined by users - namely components are going to infect other resources they depend on with their context and assign themselves as their parents. This can lead to wrong diffs and therefore to downtime and data loss should someone ignore or miss changes in plan in dry run! 

**Due to the above we have decided not to mark it as released on github and treat 0.4.0 as dead on arrival.** 

The fix for the second problem was trivial but requires a complete republishing run of all providers. The fix for the first one uncovered another problem. Sources for azure-native 3.5.0 (after Pulumi put azure native on diet) weigh 1.3GB. We tried to compile them to run a full integration testing suite that uses all of our examples but the compilation crashed even with 196GB of RAM in a dedicated hetzner box. We have therefore decided to treat az native as the lone exception that will still use simplified schema until we implement aliasing in codegen (which is kinda tricky because scala is nominally typed and not structurally typed as go or ts). With that we have been able to complete the IT run so 0.5.0 is basically done and awaits just the publishing. 

Now about that: you might be aware of the fact that Sonatype decided to kill off OSSRH at the end of June 2025. We use scala-cli for building and publishing and scala-cli can't yet publish to the new central repo. In the meantime our ops team was forced to migrate our namespace to the new Central and this means that now the only blocker for 0.5.0 is for scala-cli to support new Central and this feature should arrive next week. 

This means that should all stars align somewhere in the next week 0.5.0 should be out (given the chain of disasters that struck us I'm quite pessimistic but maybe something will go right this time!). 

The nice thing is that @prolativ  has added recently a new thing that was missing from the perspective of feature parity with mainline SDKs - resource transformations for args classes. This feature is quite useful in situations where you have a component and you want to slightly alter some of the resources that are created as part of it but can't as the author has not made them part of the component parameters (component args, basically). Resource transformations allow you to arbitrarily modify the args of any resource just before they are serialized and transferred to the provider via the wire. Resource transformations will ship with 0.5.0. 

Given that this was the last missing bit we wanted to have before 1.0.0, we foresee that after 0.5.0 we will open RC phase for 1.0.0.

**Comment by adriaanm** [comment]
Thank you for the detailed updated and the massive effort! Looking forward to the 0.5.0 release 🥳

**Comment by lbialy** [comment]
Fixed (partially) in 0.5.0 - greater granularity allows to avoid broken properties. Also some properties that are known to be broken are removed or aliased with hotfixes during codegen.

**Comment by lbialy** [comment]
Please reopen if you think this requires another fix.
